<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE registerDatapath [
<!ELEMENT register_data (equivalence, function_equivalence, register_equivalence, datapath_map)>
<!ELEMENT equivalence (bits+, mnemonic+)>
<!ELEMENT bits (#PCDATA)>
<!ELEMENT mnemonic (#PCDATA)>
<!ELEMENT function_equivalence (bits+, mnemonic+)>
<!ELEMENT bits (#PCDATA)>
<!ELEMENT mnemonic (#PCDATA)>
<!ELEMENT register_equivalence (bits+, mnemonic+)>
<!ELEMENT bits (#PCDATA)>
<!ELEMENT mnemonic (#PCDATA)>
<!ELEMENT datapath_map (num_vertex+, name+, init+, end+, color_Itype+, color_Rtype+, color_Jtype+, color_LOADtype+, color_STOREtype, color_BRANCHtype, other_axis+, isMovingXaxis+, target_vertex+, is_text+)>
<!ELEMENT num_vertex (#PCDATA)>
<!ELEMENT init (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT color_Itype (#PCDATA)>
<!ELEMENT color_Rtype (#PCDATA)>
<!ELEMENT color_Jtype (#PCDATA)>
<!ELEMENT color_LOADtype (#PCDATA)>
<!ELEMENT color_STOREtype (#PCDATA)>
<!ELEMENT color_BRANCHtype (#PCDATA)>
<!ELEMENT other_axis (#PCDATA)>
<!ELEMENT isMovingXaxis (#PCDATA)>
<!ELEMENT target_vertex (#PCDATA)>
<!ELEMENT is_text (#PCDATA)>
]>

<register_data>
	<register_equivalence>
		<bits>00000</bits>
		<mnemonic>$zero</mnemonic>
		
		<bits>00001</bits>
		<mnemonic>at</mnemonic>
		
		<bits>00010</bits>
		<mnemonic>$v0</mnemonic>
		
		<bits>00011</bits>
		<mnemonic>$v1</mnemonic>
		
		<bits>00100</bits>
		<mnemonic>$a0</mnemonic>

		<bits>00101</bits>
		<mnemonic>$a1</mnemonic>
	
		<bits>00110</bits>
		<mnemonic>$a2</mnemonic>

		<bits>00111</bits>
		<mnemonic>$a3</mnemonic>
		
		<bits>01000</bits>
		<mnemonic>$t0</mnemonic>
		
		<bits>01001</bits>
		<mnemonic>$t1</mnemonic>
		
		<bits>01010</bits>
		<mnemonic>$t2</mnemonic>	

		<bits>01011</bits>
		<mnemonic>$t3</mnemonic>	

		<bits>01100</bits>
		<mnemonic>$t4</mnemonic>	

		<bits>01101</bits>
		<mnemonic>$t5</mnemonic>
		
		<bits>01110</bits>
		<mnemonic>$t6</mnemonic>	
		
		<bits>01111</bits>
		<mnemonic>$t7</mnemonic>	
		
		<bits>10000</bits>
		<mnemonic>$s0</mnemonic>
		
		<bits>10001</bits>
		<mnemonic>$s1</mnemonic>
		
		<bits>10010</bits>
		<mnemonic>$s2</mnemonic>
		
		<bits>10011</bits>
		<mnemonic>$s3</mnemonic>		
		
		<bits>10100</bits>
		<mnemonic>$s4</mnemonic>
		
		<bits>10101</bits>
		<mnemonic>$s5</mnemonic>
						
		<bits>11000</bits>
		<mnemonic>$s6</mnemonic>
		
		<bits>10111</bits>
		<mnemonic>$s7</mnemonic>	
		
		<bits>11000</bits>
		<mnemonic>$t8</mnemonic>
		
		<bits>11001</bits>
		<mnemonic>$t9</mnemonic>
		
		<bits>11010</bits>
		<mnemonic>$k0</mnemonic>
		
		<bits>11011</bits>
		<mnemonic>$k1</mnemonic>
		
		<bits>11100</bits>
		<mnemonic>$gp</mnemonic>

		<bits>11101</bits>
		<mnemonic>$sp</mnemonic>	

		<bits>11110</bits>
		<mnemonic>$fp</mnemonic>	
		
		<bits>11111</bits>
		<mnemonic>$ra</mnemonic>			
	</register_equivalence>
	
	<datapath_map>
		<num_vertex>0</num_vertex>
		<name>init</name>
		<init>1</init>
		<end>2</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>28</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>1#2#3#4#5#6</target_vertex>
		<is_text>false</is_text>
	
		<num_vertex>1</num_vertex>
		<name>bit5_1and1</name>
		<init>3</init>
		<end>207</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>28</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>7#8</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>2</num_vertex>
		<name>bit4_1and1</name>
		<init>3</init>
		<end>217</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>52</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>9#10</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>3</num_vertex>
		<name>bit3_1and1</name>
		<init>3</init>
		<end>228</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>76</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>11#12</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>4</num_vertex>
		<name>bit2_1and1</name>
		<init>3</init>
		<end>238</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>100</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>13#14</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>5</num_vertex>
		<name>bit1_1and1</name>
		<init>3</init>
		<end>247</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>124</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>15#16</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>6</num_vertex>
		<name>bit0_1and1</name>
		<init>3</init>
		<end>255</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>145</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>17#18</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>7</num_vertex>
		<name>bit5_2and1</name>
		<init>217</init>
		<end>312</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>28</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>19#20</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>8</num_vertex>
		<name>bit5_3and1</name>
		<init>37</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>211</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>55</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>9</num_vertex>
		<name>bit4_2and1</name>
		<init>228</init>
		<end>320</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>52</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>21#22</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>10</num_vertex>
		<name>bit4_3and1</name>
		<init>60</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>222</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>11</num_vertex>
		<name>bit3_2and1</name>
		<init>238</init>
		<end>330</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>76</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>23#24</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>12</num_vertex>
		<name>bit3_3and1</name>
		<init>82</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>231</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>13</num_vertex>
		<name>bit2_2and1</name>
		<init>247</init>
		<end>342</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>100</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>25#26</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>14</num_vertex>
		<name>bit2_3and1</name>
		<init>105</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>242</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>15</num_vertex>
		<name>bit1_2and1</name>
		<init>258</init>
		<end>352</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>124</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>27#28</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>16</num_vertex>
		<name>bit1_3and1</name>
		<init>130</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>252</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>17</num_vertex>
		<name>bit0_2and1</name>
		<init>267</init>
		<end>360</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>145</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>29#30</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>18</num_vertex>
		<name>bit0_3and1</name>
		<init>150</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>262</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>19</num_vertex>
		<name>bit5_2and2</name>
		<init>320</init>
		<end>408</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>28</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>31#32</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>20</num_vertex>
		<name>bit5_3and2</name>
		<init>37</init>
		<end>167</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>316</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>56</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>21</num_vertex>
		<name>bit4_2and2</name>
		<init>332</init>
		<end>417</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>52</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>33#34</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>22</num_vertex>
		<name>bit4_3and2</name>
		<init>60</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>325</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>23</num_vertex>
		<name>bit3_2and2</name>
		<init>342</init>
		<end>427</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>76</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>35#36</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>24</num_vertex>
		<name>bit3_3and2</name>
		<init>82</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>336</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>25</num_vertex>
		<name>bit2_2and2</name>
		<init>352</init>
		<end>437</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>100</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>37#38</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>26</num_vertex>
		<name>bit2_3and2</name>
		<init>105</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>346</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>27</num_vertex>
		<name>bit1_2and2</name>
		<init>362</init>
		<end>446</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>124</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>39#40</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>28</num_vertex>
		<name>bit1_3and2</name>
		<init>130</init>
		<end>168</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>357</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>29</num_vertex>
		<name>bit0_2and2</name>
		<init>372</init>
		<end>457</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>145</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>41#42</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>30</num_vertex>
		<name>bit0_3and2</name>
		<init>152</init>
		<end>167</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>367</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>31</num_vertex>
		<name>bit5_2and3</name>
		<init>418</init>
		<end>502</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>28</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>43#44</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>32</num_vertex>
		<name>bit5_3and3</name>
		<init>37</init>
		<end>167</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>412</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>57</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>33</num_vertex>
		<name>bit4_2and3</name>
		<init>426</init>
		<end>511</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>52</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>45#46</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>34</num_vertex>
		<name>bit4_3and3</name>
		<init>60</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>422</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>35</num_vertex>
		<name>bit3_2and3</name>
		<init>436</init>
		<end>521</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>76</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>47#48</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>36</num_vertex>
		<name>bit3_3and3</name>
		<init>82</init>
		<end>165</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>432</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>37</num_vertex>
		<name>bit2_2and3</name>
		<init>446</init>
		<end>531</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>100</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>49#50</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>38</num_vertex>
		<name>bit2_3and3</name>
		<init>105</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>442</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>39</num_vertex>
		<name>bit1_2and3</name>
		<init>456</init>
		<end>540</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>124</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>51#52</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>40</num_vertex>
		<name>bit1_3and3</name>
		<init>130</init>
		<end>168</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>452</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>41</num_vertex>
		<name>bit0_2and3</name>
		<init>466</init>
		<end>551</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>145</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>53#54</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>42</num_vertex>
		<name>bit0_3and3</name>
		<init>152</init>
		<end>167</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>461</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>43</num_vertex>
		<name>bit5_2and4</name>
		<init>515</init>
		<end>660</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>28</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>44</num_vertex>
		<name>bit5_3and4</name>
		<init>37</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>507</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>58</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>45</num_vertex>
		<name>bit4_2and4</name>
		<init>524</init>
		<end>660</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>52</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>46</num_vertex>
		<name>bit4_3and4</name>
		<init>60</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>517</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>47</num_vertex>
		<name>bit3_2and4</name>
		<init>534</init>
		<end>660</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>76</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>48</num_vertex>
		<name>bit3_3and4</name>
		<init>82</init>
		<end>160</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>527</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>49</num_vertex>
		<name>bit2_2and4</name>
		<init>544</init>
		<end>660</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>100</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>50</num_vertex>
		<name>bit2_3and4</name>
		<init>105</init>
		<end>167</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>255#0#0</color_BRANCHtype>
		<other_axis>537</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>51</num_vertex>
		<name>bit1_2and4</name>
		<init>554</init>
		<end>660</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>124</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>52</num_vertex>
		<name>bit1_3and4</name>
		<init>130</init>
		<end>158</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>100#100#100</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>547</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>53</num_vertex>
		<name>bit0_2and4</name>
		<init>564</init>
		<end>660</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>145</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>54</num_vertex>
		<name>bit0_3and4</name>
		<init>152</init>
		<end>158</end>
		<color_Itype>100#100#100</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#0#0</color_LOADtype>
		<color_STOREtype>255#0#0</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>557</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>55</num_vertex>
		<name>and1_out</name>
		<init>225</init>
		<end>233</end>