<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE mipsXray_data [
<!ELEMENT mipsXray_data (equivalence, function_equivalence, register_equivalence, datapath_map)>
<!ELEMENT equivalence (bits+, mnemonic+)>
<!ELEMENT bits (#PCDATA)>
<!ELEMENT mnemonic (#PCDATA)>
<!ELEMENT function_equivalence (bits+, mnemonic+)>
<!ELEMENT bits (#PCDATA)>
<!ELEMENT mnemonic (#PCDATA)>
<!ELEMENT register_equivalence (bits+, mnemonic+)>
<!ELEMENT bits (#PCDATA)>
<!ELEMENT mnemonic (#PCDATA)>
<!ELEMENT datapath_map (num_vertex+, name+, init+, end+, color_Itype+, color_Rtype+, color_Jtype+, color_LOADtype+, color_STOREtype, color_BRANCHtype, other_axis+, isMovingXaxis+, target_vertex+, is_text+)>
<!ELEMENT num_vertex (#PCDATA)>
<!ELEMENT init (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT color_Itype (#PCDATA)>
<!ELEMENT color_Rtype (#PCDATA)>
<!ELEMENT color_Jtype (#PCDATA)>
<!ELEMENT color_LOADtype (#PCDATA)>
<!ELEMENT color_STOREtype (#PCDATA)>
<!ELEMENT color_BRANCHtype (#PCDATA)>
<!ELEMENT other_axis (#PCDATA)>
<!ELEMENT isMovingXaxis (#PCDATA)>
<!ELEMENT target_vertex (#PCDATA)>
<!ELEMENT is_text (#PCDATA)>
]>

<mipsXray_data>
	<equivalence>
		<bits>001000</bits> 	
		<mnemonic>addi</mnemonic>
		
		<bits>001001</bits>
		<mnemonic>addiu</mnemonic>
		
		<bits>001010</bits>
		<mnemonic>slti</mnemonic>
		
		<bits>001011</bits>
		<mnemonic>sltiu</mnemonic>
		
		<bits>001100</bits>
		<mnemonic>andi</mnemonic>
		
		<bits>001101</bits>
		<mnemonic>ori</mnemonic>
		
		<bits>001110</bits>
		<mnemonic>xori</mnemonic>
		
		<bits>001111</bits>
		<mnemonic>lui</mnemonic>
		
		<bits>100000</bits>
		<mnemonic>lb</mnemonic>		
		
		<bits>100001</bits>
		<mnemonic>lh</mnemonic>			
				
		<bits>100010</bits>
		<mnemonic>lwl</mnemonic>
						
		<bits>100011</bits>
		<mnemonic>lw</mnemonic>
								
		<bits>100100</bits>
		<mnemonic>lbu</mnemonic>	
										
		<bits>100101</bits>
		<mnemonic>lhu</mnemonic>
										
		<bits>100110</bits>
		<mnemonic>lwr</mnemonic>	
												
		<bits>110001</bits>
		<mnemonic>l1</mnemonic>	
																		
		<bits>110001</bits>
		<mnemonic>lwc1</mnemonic>	
																				
		<bits>110010</bits>
		<mnemonic>lwc2</mnemonic>		
																					
		<bits>110011</bits>
		<mnemonic>pref</mnemonic>	
																					
		<bits>110101</bits>
		<mnemonic>ldc1</mnemonic>	
		
		<bits>110110</bits>
		<mnemonic>ldc2</mnemonic>	
				
		<bits>101111</bits>
		<mnemonic>CACHE</mnemonic>	
						
		<bits>111000</bits>
		<mnemonic>sc</mnemonic>	
									
		<bits>111001</bits>
		<mnemonic>swc1</mnemonic>	
							
		<bits>111010</bits>
		<mnemonic>swc2</mnemonic>	
		
		<bits>111101</bits>
		<mnemonic>sdc1</mnemonic>	
		
		<bits>111110</bits>
		<mnemonic>sdc2</mnemonic>	
		
		<bits>101000</bits>
		<mnemonic>sb</mnemonic>	
		
		<bits>101001</bits>
		<mnemonic>sh</mnemonic>	
		
		<bits>101010</bits>
		<mnemonic>swl</mnemonic>	
		
		<bits>101011</bits>
		<mnemonic>sw</mnemonic>	
					
		<bits>101110</bits>
		<mnemonic>swr</mnemonic>
		
		<bits>000100</bits>
		<mnemonic>beq</mnemonic>
		
		<bits>000110</bits>
		<mnemonic>blez</mnemonic>
		
		<bits>000111</bits>
		<mnemonic>bgtz</mnemonic>
		
		<bits>000101</bits>
		<mnemonic>bne</mnemonic>				
		
		<bits>000010</bits>
		<mnemonic>j</mnemonic>	
		
		<bits>000011</bits>
		<mnemonic>jal</mnemonic>	
		
		<bits>010000</bits>
		<mnemonic>-</mnemonic>		
		
		<bits>010001</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>010010</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>010011</bits>
		<mnemonic>-</mnemonic>
		
		<bits>000001</bits>
		<mnemonic>SUB.F</mnemonic>		
		
		<bits>010100</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>010101</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>010110</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>010111</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011000</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011001</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011010</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011011</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011100</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011101</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011110</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>011111</bits>
		<mnemonic>-</mnemonic>	

		<bits>101100</bits>
		<mnemonic>-</mnemonic>	

		<bits>101101</bits>
		<mnemonic>-</mnemonic>	
		
		<bits>111100</bits>
		<mnemonic>-</mnemonic>
		
		<bits>111111</bits>
		<mnemonic>-</mnemonic>
		
		<bits>100111</bits>
		<mnemonic>-</mnemonic>
		
		<bits>110100</bits>
		<mnemonic>-</mnemonic>
		
		<bits>110111</bits>
		<mnemonic>-</mnemonic>
		
		<bits>110111</bits>
		<mnemonic>-</mnemonic>
		
		<bits>111011</bits>
		<mnemonic>-</mnemonic>
											
		<bits>000000</bits>
		<mnemonic>r-type</mnemonic>		
	</equivalence>
	
	<function_equivalence>
		<bits>000000</bits>
		<mnemonic>sll</mnemonic>
		
		<bits>000010</bits>
		<mnemonic>srl</mnemonic>
		
		<bits>000011</bits>
		<mnemonic>sra</mnemonic>	
		
		<bits>000100</bits>
		<mnemonic>sllv</mnemonic>	
		
		<bits>000110</bits>
		<mnemonic>srlv</mnemonic>	
		
		<bits>000111</bits>
		<mnemonic>srav</mnemonic>	
		
		<bits>001000</bits>
		<mnemonic>jr</mnemonic>
		
		<bits>001001</bits>
		<mnemonic>jalr</mnemonic>	
		
		<bits>001010</bits>
		<mnemonic>movz</mnemonic>	
		
		<bits>001011</bits>
		<mnemonic>movn</mnemonic>	
		
		<bits>001100</bits>
		<mnemonic>SYSCALL</mnemonic>	
		
		<bits>001101</bits>
		<mnemonic>BREAK</mnemonic>	
		
		<bits>010000</bits>
		<mnemonic>mfhi</mnemonic>	
		
		<bits>010001</bits>
		<mnemonic>mthi</mnemonic>
		
		<bits>010010</bits>
		<mnemonic>mflo</mnemonic>
		
		<bits>010011</bits>
		<mnemonic>mtlo</mnemonic>
		
		<bits>011000</bits>
		<mnemonic>mult</mnemonic>
		
		<bits>011001</bits>
		<mnemonic>multu</mnemonic>
		
		<bits>011010</bits>
		<mnemonic>div</mnemonic>
		
		<bits>011011</bits>
		<mnemonic>divu</mnemonic>
		
		<bits>100000</bits>
		<mnemonic>add</mnemonic>
		
		<bits>100001</bits>
		<mnemonic>addu</mnemonic>
		
		<bits>100010</bits>
		<mnemonic>sub</mnemonic>
		
		<bits>100011</bits>
		<mnemonic>subu</mnemonic>
		
		<bits>100100</bits>
		<mnemonic>and</mnemonic>
				
		<bits>100101</bits>
		<mnemonic>or</mnemonic>
		
		<bits>100110</bits>
		<mnemonic>xor</mnemonic>

		<bits>100111</bits>
		<mnemonic>nor</mnemonic>
		
		<bits>101010</bits>
		<mnemonic>slt</mnemonic>
		
		<bits>101011</bits>
		<mnemonic>sltu</mnemonic>
				
		<bits>110000</bits>
		<mnemonic>tge</mnemonic>
				
		<bits>110001</bits>
		<mnemonic>tgeu</mnemonic>
		
		<bits>110010</bits>
		<mnemonic>tlt</mnemonic>

		<bits>110011</bits>
		<mnemonic>tltu</mnemonic>		
		
		<bits>110100</bits>
		<mnemonic>teq</mnemonic>	
				
		<bits>110110</bits>
		<mnemonic>tne</mnemonic>					
	</function_equivalence>
	
	<register_equivalence>
		<bits>00000</bits>
		<mnemonic>$zero</mnemonic>
		
		<bits>00001</bits>
		<mnemonic>at</mnemonic>
		
		<bits>00010</bits>
		<mnemonic>$v0</mnemonic>
		
		<bits>00011</bits>
		<mnemonic>$v1</mnemonic>
		
		<bits>00100</bits>
		<mnemonic>$a0</mnemonic>

		<bits>00101</bits>
		<mnemonic>$a1</mnemonic>
	
		<bits>00110</bits>
		<mnemonic>$a2</mnemonic>

		<bits>00111</bits>
		<mnemonic>$a3</mnemonic>
		
		<bits>01000</bits>
		<mnemonic>$t0</mnemonic>
		
		<bits>01001</bits>
		<mnemonic>$t1</mnemonic>
		
		<bits>01010</bits>
		<mnemonic>$t2</mnemonic>	

		<bits>01011</bits>
		<mnemonic>$t3</mnemonic>	

		<bits>01100</bits>
		<mnemonic>$t4</mnemonic>	

		<bits>01101</bits>
		<mnemonic>$t5</mnemonic>
		
		<bits>01110</bits>
		<mnemonic>$t6</mnemonic>	
		
		<bits>01111</bits>
		<mnemonic>$t7</mnemonic>	
		
		<bits>10000</bits>
		<mnemonic>$s0</mnemonic>
		
		<bits>10001</bits>
		<mnemonic>$s1</mnemonic>
		
		<bits>10010</bits>
		<mnemonic>$s2</mnemonic>
		
		<bits>10011</bits>
		<mnemonic>$s3</mnemonic>		
		
		<bits>10100</bits>
		<mnemonic>$s4</mnemonic>
		
		<bits>10101</bits>
		<mnemonic>$s5</mnemonic>
						
		<bits>11000</bits>
		<mnemonic>$s6</mnemonic>
		
		<bits>10111</bits>
		<mnemonic>$s7</mnemonic>	
		
		<bits>11000</bits>
		<mnemonic>$t8</mnemonic>
		
		<bits>11001</bits>
		<mnemonic>$t9</mnemonic>
		
		<bits>11010</bits>
		<mnemonic>$k0</mnemonic>
		
		<bits>11011</bits>
		<mnemonic>$k1</mnemonic>
		
		<bits>11100</bits>
		<mnemonic>$gp</mnemonic>

		<bits>11101</bits>
		<mnemonic>$sp</mnemonic>	

		<bits>11110</bits>
		<mnemonic>$fp</mnemonic>	
		
		<bits>11111</bits>
		<mnemonic>$ra</mnemonic>			
	</register_equivalence>
	
	<datapath_map>
		<num_vertex>0</num_vertex>
		<name>*Program_counter</name>
		<init>161</init>
		<end>188</end>
		<color_Itype>255#255#0</color_Itype>
		<color_Rtype>255#255#0</color_Rtype>
		<color_Jtype>255#255#0</color_Jtype>
		<color_LOADtype>255#255#0</color_LOADtype>
		<color_STOREtype>255#255#0</color_STOREtype>
		<color_BRANCHtype>255#255#0</color_BRANCHtype>
		<other_axis>362</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>1#6</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>1</num_vertex>
		<name>*nodeADD1input1A</name>
		<init>358</init>
		<end>95</end>
		<color_Itype>255#255#0</color_Itype>
		<color_Rtype>255#255#0</color_Rtype>
		<color_Jtype>255#255#0</color_Jtype>
		<color_LOADtype>255#255#0</color_LOADtype>
		<color_STOREtype>255#255#0</color_STOREtype>
		<color_BRANCHtype>255#255#0</color_BRANCHtype>
		<other_axis>192</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>2#3</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>2</num_vertex>
		<name>*ADD1input1B</name>
		<init>192</init>
		<end>253</end>
		<color_Itype>255#255#0</color_Itype>
		<color_Rtype>255#255#0</color_Rtype>
		<color_Jtype>255#255#0</color_Jtype>
		<color_LOADtype>255#255#0</color_LOADtype>
		<color_STOREtype>255#255#0</color_STOREtype>
		<color_BRANCHtype>255#255#0</color_BRANCHtype>
		<other_axis>94</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
	
			
		<num_vertex>3</num_vertex>
		<name>*ADDA1input2</name>
		<init>210</init>
		<end>253</end>
		<color_Itype>255#255#0</color_Itype>
		<color_Rtype>255#255#0</color_Rtype>
		<color_Jtype>255#255#0</color_Jtype>
		<color_LOADtype>255#255#0</color_LOADtype>
		<color_STOREtype>255#255#0</color_STOREtype>
		<color_BRANCHtype>255#255#0</color_BRANCHtype>
		<other_axis>144</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>5</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>4</num_vertex>
		<name>outputDATAMEM1</name>
		<init>400</init>
		<end>415</end>
		<color_Itype>16#78#139</color_Itype>
		<color_Rtype>16#78#139</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>30#144#255</color_LOADtype>
		<color_STOREtype>100#100#100</color_STOREtype>
		<color_BRANCHtype>100#100#100</color_BRANCHtype>
		<other_axis>414</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>101</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>5</num_vertex>
		<name>*node1ADD2</name>
		<init>311</init>
		<end>493</end>
		<color_Itype>238#221#130</color_Itype>
		<color_Rtype>238#221#130</color_Rtype>
		<color_Jtype>238#221#130</color_Jtype>
		<color_LOADtype>238#221#130</color_LOADtype>
		<color_STOREtype>238#221#130</color_STOREtype>
		<color_BRANCHtype>238#221#130</color_BRANCHtype>
		<other_axis>119</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>13#14</target_vertex>
		<is_text>false</is_text>
				
		<num_vertex>6</num_vertex>
		<name>*instruction_Memory</name>
		<init>198</init>
		<end>215</end>
		<color_Itype>255#255#0</color_Itype>
		<color_Rtype>255#255#0</color_Rtype>
		<color_Jtype>255#255#0</color_Jtype>
		<color_LOADtype>255#255#0</color_LOADtype>
		<color_STOREtype>255#255#0</color_STOREtype>
		<color_BRANCHtype>255#255#0</color_BRANCHtype>
		<other_axis>362</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>7</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>7</num_vertex>
		<name>*nodeIMrepeated</name>
		<init>311</init>
		<end>315</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>378</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>8</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>8</num_vertex>
		<name>nodeIM</name>
		<init>311</init>
		<end>315</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>378</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>9#10</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>9</num_vertex>
		<name>nodeSHIFTLEFT1</name>
		<init>375</init>
		<end>75</end>
		<color_Itype>255#185#15</color_Itype>
		<color_Rtype>255#185#15</color_Rtype>
		<color_Jtype>255#185#15</color_Jtype>
		<color_LOADtype>255#185#15</color_LOADtype>
		<color_STOREtype>255#185#15</color_STOREtype>
		<color_BRANCHtype>255#185#15</color_BRANCHtype>
		<other_axis>317</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>11</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>10</num_vertex>
		<name>*nodeIM2</name>
		<init>322</init>
		<end>325</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>378</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>19#20</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>11</num_vertex>
		<name>*SHIFTLEFT1</name>
		<init>317</init>
		<end>388</end>
		<color_Itype>255#185#15</color_Itype>
		<color_Rtype>255#185#15</color_Rtype>
		<color_Jtype>255#185#15</color_Jtype>
		<color_LOADtype>255#185#15</color_LOADtype>
		<color_STOREtype>255#185#15</color_STOREtype>
		<color_BRANCHtype>255#185#15</color_BRANCHtype>
		<other_axis>75</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>12</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>12</num_vertex>
		<name>*nodeMUXC</name>
		<init>440</init>
		<end>485</end>
		<color_Itype>255#185#15</color_Itype>
		<color_Rtype>255#185#15</color_Rtype>
		<color_Jtype>255#185#15</color_Jtype>
		<color_LOADtype>255#185#15</color_LOADtype>
		<color_STOREtype>255#185#15</color_STOREtype>
		<color_BRANCHtype>255#185#15</color_BRANCHtype>
		<other_axis>75</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>

		<num_vertex>13</num_vertex>
		<name>*nodeMUXC1</name>
		<init>115</init>
		<end>88</end>
		<color_Itype>238#221#130</color_Itype>
		<color_Rtype>238#221#130</color_Rtype>
		<color_Jtype>238#221#130</color_Jtype>
		<color_LOADtype>238#221#130</color_LOADtype>
		<color_STOREtype>238#221#130</color_STOREtype>
		<color_BRANCHtype>238#221#130</color_BRANCHtype>
		<other_axis>497</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>18</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>14</num_vertex>
		<name>node2ADD2</name>
		<init>503</init>
		<end>595</end>
		<color_Itype>238#221#130</color_Itype>
		<color_Rtype>238#221#130</color_Rtype>
		<color_Jtype>238#221#130</color_Jtype>
		<color_LOADtype>238#221#130</color_LOADtype>
		<color_STOREtype>238#221#130</color_STOREtype>
		<color_BRANCHtype>238#221#130</color_BRANCHtype>
		<other_axis>119</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>15#16</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>15</num_vertex>
		<name>*nodeMUXB</name>
		<init>115</init>
		<end>100</end>
		<color_Itype>238#221#130</color_Itype>
		<color_Rtype>238#221#130</color_Rtype>
		<color_Jtype>238#221#130</color_Jtype>
		<color_LOADtype>238#221#130</color_LOADtype>
		<color_STOREtype>238#221#130</color_STOREtype>
		<color_BRANCHtype>238#221#130</color_BRANCHtype>
		<other_axis>600</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>17</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>16</num_vertex>
		<name>*ADD2input1</name>
		<init>605</init>
		<end>650</end>
		<color_Itype>238#221#130</color_Itype>
		<color_Rtype>238#221#130</color_Rtype>
		<color_Jtype>238#221#130</color_Jtype>
		<color_LOADtype>238#221#130</color_LOADtype>
		<color_STOREtype>238#221#130</color_STOREtype>
		<color_BRANCHtype>238#221#130</color_BRANCHtype>
		<other_axis>119</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>17</num_vertex>
		<name>*MUXB</name>
		<init>600</init>
		<end>762</end>
		<color_Itype>238#221#130</color_Itype>
		<color_Rtype>238#221#130</color_Rtype>
		<color_Jtype>238#221#130</color_Jtype>
		<color_LOADtype>238#221#130</color_LOADtype>
		<color_STOREtype>238#221#130</color_STOREtype>
		<color_BRANCHtype>238#221#130</color_BRANCHtype>
		<other_axis>100</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>87</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>18</num_vertex>
		<name>*nodeMUXC1</name>
		<init>502</init>
		<end>793</end>
		<color_Itype>205#149#15</color_Itype>
		<color_Rtype>205#149#15</color_Rtype>
		<color_Jtype>205#149#15</color_Jtype>
		<color_LOADtype>205#149#15</color_LOADtype>
		<color_STOREtype>205#149#15</color_STOREtype>
		<color_BRANCHtype>205#149#15</color_BRANCHtype>
		<other_axis>75</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>42</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>19</num_vertex>
		<name>*nodeREG2</name>
		<init>376</init>
		<end>360</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>329</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>24#26</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>20</num_vertex>
		<name>*nodeMUXA1</name>
		<init>385</init>
		<end>395</end>
		<color_Itype>255#127#36</color_Itype>
		<color_Rtype>0#191#255</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#127#36</color_LOADtype>
		<color_STOREtype>255#127#36</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>329</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>21#22</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>21</num_vertex>
		<name>MUXA2</name>
		<init>334</init>
		<end>365</end>
		<color_Itype>255#127#36</color_Itype>
		<color_Rtype>0#191#255</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#127#36</color_LOADtype>
		<color_STOREtype>255#127#36</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>399</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
	
		<num_vertex>22</num_vertex>
		<name>*nodeSIGN_EXT</name>
		<init>403</init>
		<end>461</end>
		<color_Itype>0#255#255</color_Itype>
		<color_Rtype>255#127#36</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#127#36</color_LOADtype>
		<color_STOREtype>255#127#36</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>329</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>23#33</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>23</num_vertex>
		<name>*SIGN_EXT</name>
		<init>333</init>
		<end>425</end>
		<color_Itype>0#255#255</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>255#127#36</color_LOADtype>
		<color_STOREtype>255#127#36</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>466</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>37</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>24</num_vertex>
		<name>*nodeREG2A</name>
		<init>354</init>
		<end>339</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>328</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>30#31</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>25</num_vertex>
		<name>notUsed</name>
		<init>331</init>
		<end>415</end>
		<color_Itype>255#255#0</color_Itype>
		<color_Rtype>255#255#0</color_Rtype>
		<color_Jtype>255#255#0</color_Jtype>
		<color_LOADtype>255#255#0</color_LOADtype>
		<color_STOREtype>255#255#0</color_STOREtype>
		<color_BRANCHtype>255#255#0</color_BRANCHtype>
		<other_axis>336</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>26</num_vertex>
		<name>*nodeREGB</name>
		<init>334</init>
		<end>344</end>
		<color_Itype>0#0#255</color_Itype>
		<color_Rtype>0#0#255</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>0#0#255</color_LOADtype>
		<color_STOREtype>0#0#255</color_STOREtype>
		<color_BRANCHtype>0#0#255</color_BRANCHtype>
		<other_axis>358</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>27#29</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>27</num_vertex>
		<name>*nodeMUXA</name>
		<init>363</init>
		<end>371</end>
		<color_Itype>0#0#255</color_Itype>
		<color_Rtype>0#0#255</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>0#0#255</color_LOADtype>
		<color_STOREtype>0#0#255</color_STOREtype>
		<color_BRANCHtype>0#0#255</color_BRANCHtype>
		<other_axis>348</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>28</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>28</num_vertex>
		<name>*nodeMUXA</name>
		<init>348</init>
		<end>362</end>
		<color_Itype>0#0#255</color_Itype>
		<color_Rtype>0#0#255</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>0#0#255</color_LOADtype>
		<color_STOREtype>0#0#255</color_STOREtype>
		<color_BRANCHtype>0#0#255</color_BRANCHtype>
		<other_axis>371</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>29</num_vertex>
		<name>*REGB</name>
		<init>352</init>
		<end>416</end>
		<color_Itype>0#0#255</color_Itype>
		<color_Rtype>0#0#255</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>0#0#255</color_LOADtype>
		<color_STOREtype>0#0#255</color_STOREtype>
		<color_BRANCHtype>0#0#255</color_BRANCHtype>
		<other_axis>358</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>30</num_vertex>
		<name>*nodeCTRL2</name>
		<init>329</init>
		<end>230</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>328</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>32</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>31</num_vertex>
		<name>*REGinput1</name>
		<init>333</init>
		<end>415</end>
		<color_Itype>0#255#0</color_Itype>
		<color_Rtype>0#255#0</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>0#255#0</color_LOADtype>
		<color_STOREtype>0#255#0</color_STOREtype>
		<color_BRANCHtype>0#255#0</color_BRANCHtype>
		<other_axis>335</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>32</num_vertex>
		<name>*CTRL</name>
		<init>328</init>
		<end>348</end>
		<color_Itype>255#0#255</color_Itype>
		<color_Rtype>255#0#255</color_Rtype>
		<color_Jtype>255#0#255</color_Jtype>
		<color_LOADtype>255#0#255</color_LOADtype>
		<color_STOREtype>255#0#255</color_STOREtype>
		<color_BRANCHtype>255#0#255</color_BRANCHtype>
		<other_axis>230</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>44#45#46#47#48#49#50#51#52</target_vertex>
		<is_text>false</is_text>
				
		<num_vertex>33</num_vertex>
		<name>*nodeALU_CTRL</name>
		<init>467</init>
		<end>503</end>
		<color_Itype>205#91#69</color_Itype>
		<color_Rtype>205#91#69</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>205#91#69</color_LOADtype>
		<color_STOREtype>205#91#69</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>329</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>34</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>34</num_vertex>
		<name>*ALU_CTRL</name>
		<init>329</init>
		<end>562</end>
		<color_Itype>205#91#69</color_Itype>
		<color_Rtype>205#91#69</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>205#91#69</color_LOADtype>
		<color_STOREtype>205#91#69</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>503</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>35</num_vertex>
		<name>*nodeALUcontrol1</name>
		<init>617</init>
		<end>650</end>
		<color_Itype>205#91#69</color_Itype>
		<color_Rtype>205#91#69</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>205#91#69</color_LOADtype>
		<color_STOREtype>205#91#69</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>501</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>36</target_vertex>
		<is_text>false</is_text>
	
		<num_vertex>36</num_vertex>
		<name>*nodeALUcontrol2</name>
		<init>501</init>
		<end>385</end>
		<color_Itype>205#91#69</color_Itype>
		<color_Rtype>205#91#69</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>205#91#69</color_LOADtype>
		<color_STOREtype>205#91#69</color_STOREtype>
		<color_BRANCHtype>255#127#36</color_BRANCHtype>
		<other_axis>650</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>99</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>37</num_vertex>
		<name>*nodeSIGN_EXT</name>
		<init>500</init>
		<end>536</end>
		<color_Itype>139#115#85</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>139#115#85</color_LOADtype>
		<color_STOREtype>139#115#85</color_STOREtype>
		<color_BRANCHtype>139#115#85</color_BRANCHtype>
		<other_axis>466</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>38</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>38</num_vertex>
		<name>*nodeSHIFT_LEFT2</name>
		<init>466</init>
		<end>404</end>
		<color_Itype>139#115#85</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>139#115#85</color_LOADtype>
		<color_STOREtype>139#115#85</color_STOREtype>
		<color_BRANCHtype>139#115#85</color_BRANCHtype>
		<other_axis>535</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>39#73</target_vertex>
		<is_text>false</is_text>
	
		<num_vertex>39</num_vertex>
		<name>*nodeSHIFT_LEFT2A</name>
		<init>395</init>
		<end>153</end>
		<color_Itype>139#115#85</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>139#115#85</color_LOADtype>
		<color_STOREtype>139#115#85</color_STOREtype>
		<color_BRANCHtype>139#115#85</color_BRANCHtype>
		<other_axis>535</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>40</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>40</num_vertex>
		<name>*SHIFT_LEFT2</name>
		<init>535</init>
		<end>550</end>
		<color_Itype>139#115#85</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>139#115#85</color_LOADtype>
		<color_STOREtype>139#115#85</color_STOREtype>
		<color_BRANCHtype>139#115#85</color_BRANCHtype>
		<other_axis>153</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>41</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>41</num_vertex>
		<name>ADD2</name>
		<init>605</init>
		<end>652</end>
		<color_Itype>139#115#85</color_Itype>
		<color_Rtype>100#100#100</color_Rtype>
		<color_Jtype>100#100#100</color_Jtype>
		<color_LOADtype>139#115#85</color_LOADtype>
		<color_STOREtype>139#115#85</color_STOREtype>
		<color_BRANCHtype>139#115#85</color_BRANCHtype>
		<other_axis>170</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>72</target_vertex>
		<is_text>false</is_text>
			
		<num_vertex>42</num_vertex>
		<name>*nodeMUXC2</name>
		<init>75</init>
		<end>108</end>
		<color_Itype>205#149#15</color_Itype>
		<color_Rtype>205#149#15</color_Rtype>
		<color_Jtype>205#149#15</color_Jtype>
		<color_LOADtype>205#149#15</color_LOADtype>
		<color_STOREtype>205#149#15</color_STOREtype>
		<color_BRANCHtype>205#149#15</color_BRANCHtype>
		<other_axis>794</other_axis>
		<isMovingXaxis>false</isMovingXaxis>
		<target_vertex>43</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>43</num_vertex>
		<name>*nodeMUXC3</name>
		<init>794</init>
		<end>804</end>
		<color_Itype>205#149#15</color_Itype>
		<color_Rtype>205#149#15</color_Rtype>
		<color_Jtype>205#149#15</color_Jtype>
		<color_LOADtype>205#149#15</color_LOADtype>
		<color_STOREtype>205#149#15</color_STOREtype>
		<color_BRANCHtype>205#149#15</color_BRANCHtype>
		<other_axis>108</other_axis>
		<isMovingXaxis>true</isMovingXaxis>
		<target_vertex>0</target_vertex>
		<is_text>false</is_text>
		
		<num_vertex>44</num_vertex>
		<name>*SIG_CTRL_MUXA1</name>